export default {
    loginNavigator: "LoginNavigator",
    login: "Login",
    signUp: "SignUp",
    signUpNext: "SignUpNext",
    homeNavigator: "HomeNavigator",
    home: "Home",
    teamScreen: "TeamScreen",
    teamDetailScreen:"TeamDetailScreen",
    favoriteFootballCourts: "FavoriteFootballCourts",
    footballCourt: "FootballCourt",
    searchNavigator: "SearchNavigator",
    search: "Search",
    timelineNavigator: "TimelineNavigator",
    timeline: "Timeline",
    comments: "Comments",
    sharePost: "SharePost",
    messagesNavigator: "MessagesNavigator",
    messages: "Messages",
    messaging: "Messaging",
    profileNavigator: "ProfileNavigator",
    profile: "Profile",
    profileEdit: "ProfileEdit",
    followingAndFollowersScreen: "FollowingAndFollowersScreen"
}